// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwHz2BsBIo3kXxKh6NXtrgyrRig7w2iwI',
    appId: '1:102404925022:web:05013d28ba7cbd77cbb6cf',
    messagingSenderId: '102404925022',
    projectId: 'profile-b91db',
    authDomain: 'profile-b91db.firebaseapp.com',
    storageBucket: 'profile-b91db.firebasestorage.app',
    measurementId: 'G-PTQWC1CSM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiVnvys9HPxwaZAei8PJ-dZnQM2lg3li4',
    appId: '1:102404925022:android:2111c52ab05ed16dcbb6cf',
    messagingSenderId: '102404925022',
    projectId: 'profile-b91db',
    storageBucket: 'profile-b91db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwMxXjbw1VyubTFIFWA3NmFz2aPVHsn7o',
    appId: '1:102404925022:ios:e86048515e0a584dcbb6cf',
    messagingSenderId: '102404925022',
    projectId: 'profile-b91db',
    storageBucket: 'profile-b91db.firebasestorage.app',
    iosBundleId: 'com.example.myProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwMxXjbw1VyubTFIFWA3NmFz2aPVHsn7o',
    appId: '1:102404925022:ios:e86048515e0a584dcbb6cf',
    messagingSenderId: '102404925022',
    projectId: 'profile-b91db',
    storageBucket: 'profile-b91db.firebasestorage.app',
    iosBundleId: 'com.example.myProfile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwHz2BsBIo3kXxKh6NXtrgyrRig7w2iwI',
    appId: '1:102404925022:web:a8e0afd8ae51e410cbb6cf',
    messagingSenderId: '102404925022',
    projectId: 'profile-b91db',
    authDomain: 'profile-b91db.firebaseapp.com',
    storageBucket: 'profile-b91db.firebasestorage.app',
    measurementId: 'G-F284WFYQZB',
  );
}
